### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by timothydnguyen** [cyralinc/approzium#21]
async operations
cache temp credentials

**Comment by tyrannosaurus-becks** [comment]
@timothydnguyen is this done because async operations were implemented [here](https://github.com/approzium/approzium/blob/develop/authenticator/server/authenticator.go#L123) and caching temp credentials was added to the Python SDK [here](https://github.com/approzium/approzium/blob/develop/sdk/python/approzium/_authenticator.py#L43), in that it now caches the claimed ARN, and the signed get caller identity string?

**Comment by tyrannosaurus-becks** [comment]
Closing because I believe this is done. Please reopen if that's incorrect.
